### ISSUE TITLE
Library should allow for a custom HttpMessageHandler

### ISSUE THREAD

**Issue by Arlodotexe** [ipfs-shipyard/net-ipfs-http-client#10]
# Problem
The library doesn't allow for custom HttpMessageHandlers. That means no custom headers, no custom functionality, and no polyfil on certain places where it's needed.

# Solution

Rather than constructing a new HttpClientHandler here:
https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/IpfsClient.cs#L223

We should make this a `HttpMessageHandler` and move it to a property on the `IpfsClient` class, where the default value is `new HttpClientHandler()`.

**Comment by mihneacalugaru** [comment]
@Arlodotexe, but aren't the custom headers that need to be set only accessible from the `HttpClientHandler` instance? Having access only to the instance of the base class `HttpMessageHandler` doesn't seem to be enough to set custom headers.
