### ISSUE TITLE
Add files doesn't show up in IPFS local node

### ISSUE THREAD

**Issue by zipgenius** [ipfs-shipyard/net-ipfs-http-client#14]
I'm new to IPFS development and maybe I'm missing something but I can't make to list files in IPFS client list.

I'm using the following code: 
`
string pFile = @"C:\Users\matte\Desktop\dump_languagefiles.pdf";
var ipfs = new IpfsClient();
AddFileOptions options = new AddFileOptions();
options. Pin = true;
options.OnlyHash = false;
options. Wrap = false;
IFileSystemNode ipfsNode = await ipfs.FileSystem.AddFileAsync(pFile, options, default);
`

But nothing appears here:
![image](https://user-images.githubusercontent.com/547604/207577448-b35e6247-3ad4-419e-9a08-fe39bfabbb94.png)

**Comment by Derrick-** [comment]
From what I can see, the FileSystemApi implementation is incomplete and for the most part does not uses the /files/ commands.

[AddFileAsync](https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/CoreApi/FileSystemApi.cs#L25) only adds the file to the node, and returns the FileSystemNode of the file (or directory). You can see that [code here](https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/CoreApi/FileSystemApi.cs#L64), it uses the [add]([adds](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-add)) command and not the [MFS subsystem](https://docs.ipfs.tech/concepts/file-systems/) api: /files/

It does not actually add it to the MFS files system of the node which might be implemented by a subsequent [/files/cp](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-files-cp) command to hang the file or directory at a specified path.

I would be interested in working on [FileSystemApi](https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/CoreApi/FileSystemApi.cs) or collaborating with anyone else interested in getting this working as expected

**Comment by Derrick-** [comment]
On a second look, [FileSystemApi](https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/CoreApi/FileSystemApi.cs) does not support /api/files at all

It has API call to [/file/ls](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-file-ls) which is [deprecated](https://docs.ipfs.tech/reference/kubo/rpc/#deprecated-rpc-commands) which led me to believe that this class was supposed to be talking to the /files api's, it's actually more of a utility class.

The entire MFS command set should be implemented. I suspect that MFS was not yet released at the time of [FileSystemApi](https://github.com/ipfs-shipyard/net-ipfs-http-client/blob/main/src/CoreApi/FileSystemApi.cs) creation.

A new API interface and class such as MfsApi should probably be implemented. This work would have to be integrated in [net-ipfs-core CoreApi](https://github.com/ipfs-shipyard/net-ipfs-core/tree/main/src/CoreApi) as well

**Comment by Maverick1983** [comment]
Sorry, I don't understand if code it's working or not. Can I help?
