### ISSUE TITLE
Migrate to modern CI

### ISSUE THREAD

**Issue by Arlodotexe** [ipfs-shipyard/net-ipfs-http-client#2]
# Background
The ported library is currently using a combination of AppVeyor, Travic, Codacy, and a few more.

# The problem
Rather than using 3 different DevOps services, we should stick to what GitHub offers out of the box

# The solution
- [ ] Clean up and remove all devops related content in the repository

We also need GitHub Actions workflows that:
- [ ] Ensure the project builds successfully
- [ ] Runs Unit Tests

Mirror of https://github.com/ipfs-shipyard/net-ipfs-core/issues/3

**Comment by ATikadze** [comment]
This is mine

**Comment by Arlodotexe** [comment]
Closed by #7
